### ISSUE TITLE
Right-clicking on a revealed tile will place a flag

### ISSUE THREAD

**Issue by neandrake** [eric1221bday/minesweep-rs#1]
You can right-click on a revealed tile to place a flag, which seems like that shouldn't happen. Un-placing the flag turns the tile back into unknown state as well.

**Comment by neandrake** [comment]
It's been ages but in the original game I believe right-clicking on a revealed tile would reveal more tiles around it that can be logically determined to not have mines.

**Comment by oceanusxiv** [comment]
Huh you're right, can't believe I missed this bug. Fixed. Can you clarify your second statement a bit? I was under the impression that revealing more tiles was already done automatically if you reveal a tile not adjacent to any mines.

**Comment by neandrake** [comment]
The current behavior when revealing a tile that is not adjacent to any mines does reveal more.

I believe the original windows game had a feature when right-clicking on a revealed number tile that has flagged mines (ex: right clicking a revealed `2` tile that has 2 unrevealed-but-flagged tiles adjacent) -- then all other adjacent tiles to it would be revealed as if clicked. I don't recall the exact behavior, as it may have revealed a mine if the adjacent flagged tiles were wrong.
