### ISSUE TITLE
Mouse actions happen on mouse-down and not mouse-up

### ISSUE THREAD

**Issue by neandrake** [eric1221bday/minesweep-rs#2]
This is a personal preference as I tend to press the mouse and then decide whether to let go or not. The current behavior to reveal or flag a tile happens directly on mouse down. I believe the original windows game would animate the tile being pressed on mouse down then perform the action on mouse up.

**Comment by oceanusxiv** [comment]
This was actually behavior I wanted to implement as well, unfortunately I don't think Piston currently distinguishes between mouse down and mouse up. If I'm mistaken and there is a way to do it I would be happy to implement something along these lines.

**Comment by subnomo** [comment]
@eric1221bday I believe you could do [something like this](https://github.com/PistonDevelopers/piston-examples/blob/master/user_input/src/main.rs#L64).
