### ISSUE TITLE
Add support for middle mouse button

### ISSUE THREAD

**Issue by DarrenRJ** [eric1221bday/minesweep-rs#3]
You may not be aware but the windows minesweeper has a middle mouse button behavior, that the experts use to speed games up. If you middle mouse click on a number square adjacent to an unrevealed square it would do 1 of two possible things. If the number square had as many bombs marked adjacent to it as its number it would reveal all the adjacent blocks that were not marked. If there were not enough adjacent blocks marked then it would highlight all the adjacent blocks that have not been marked
It would be good for you to implement this functionality because playing minesweeper without this makes me feel like a noob.

**Comment by dwijnand** [comment]
This should also be the effect of simultaneously clicking left and right mouse buttons.

**Comment by oceanusxiv** [comment]
commit naming error, this is a bit more of complex feature so I'm still working out how to implement it.

**Comment by oceanusxiv** [comment]
thanks to @Ristarg for the pull request. Done
