### ISSUE TITLE
Prevent hitting mine on first click

### ISSUE THREAD

**Issue by dbrgn** [eric1221bday/minesweep-rs#4]
I'm not sure if Windows did this or not, but it's very annoying if you hit a mine on first click.

Could you cheat a bit and re-create the minefield if the first hit would be a mine, to make the game less frustrating?

**Comment by oceanusxiv** [comment]
This turned out to be a bit more complicated to implement than I thought. But Done. This would also serve as a starting point for maybe implementing only generating solveable boards in the future.
