### ISSUE TITLE
Right-click on close button does not stop the game

### ISSUE THREAD

**Issue by ErichDonGubler** [eric1221bday/minesweep-rs#5]
![Example bug reproduction](https://user-images.githubusercontent.com/658538/40624628-e145eda2-626a-11e8-96ae-52e8393af998.gif)

Thanks for the fun experiment!

**Comment by oceanusxiv** [comment]
Interesting, as I did not do any special configuration on window management, this might be an upstream issue with piston_window on Windows. I'll do some more investigation.

**Comment by trevarj** [comment]
Tested this and it doesn't seem to happen anymore.
