### ISSUE TITLE
Clicking the smiley/dead face doesn't restart the game

### ISSUE THREAD

**Issue by dwijnand** [eric1221bday/minesweep-rs#6]
I can't remember if clicking the smiley face restarts the still-in-progress game.

But from muscle memory clicking the smiley/dead face should restart a finish game (win or lost).

**Comment by oceanusxiv** [comment]
implementing this was a bit agonizing because I had to decide whether to switch to a full gui like conrod or just hack together a pseudo button system for now. Decided to do the latter but will re-evaluate when conrod starts to support toolbars

**Comment by dwijnand** [comment]
sweet, thanks! 😄
